version: "3"

services:
  gateway:
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: gateway-container
    working_dir: /go/src/github.com/SND1231/portfolio-gateway
    ports:
      - "8081:8081"
    volumes:
      - ./src/go.mod:/go/src/github.com/SND1231/portfolio-gateway/go.mod
      - ./src/go.sum:/go/src/github.com/SND1231/portfolio-gateway/go.sum
      - ./src/main.go:/go/src/github.com/SND1231/portfolio-gateway/main.go
    networks:
      - app_network
networks:
  app_network:
    external: true
