apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: snd1231/app-gateway
    context: .
    docker:
      dockerfile: ./docker/Dockerfile
      buildArgs:
        SECRET_KEY: "{{.SECRET_KEY}}"
  local:
    push: true

deploy:
  kubectl:
    manifests:
      - gateway-deployment.yaml

