version: 2.1

jobs:
  image-push:
    machine: true
    steps:
      - checkout
      - run:
          name: Build
          command: docker-compose build --build-arg SECRET_KEY=$SECRET_KEY gateway
      - run:
          name: Tag to latest
          command: docker tag project_gateway:latest ${DOCKER_USER}/app-gateway:latest
      - run:
          name: Docker Login
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: Push image to registory
          command: docker push ${DOCKER_USER}/app-gateway
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
     - image-push:
          context: ramen_app
